mysqldb-comp:
  image: mysql:latest
  environment:
    MYSQL_DATABASE: sample
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret
  ports:
    - 3306:3306
  volumes:
    - /home/vagrant/volumes/mysqlvolume:/var/lib/mysql
jboss-dsmysql-comp:
  image: repogio/jboss-dsmysql
  links:
    - mysqldb-comp:db
  ports:
    - 8080:8080
    - 9990:9990
  depends_on:
    - mysqldb-comp