CREATE TABLE CUSTOMERS (
ID INT NOT NULL AUTO_INCREMENT,
NAME varchar(100),
CITY varchar(100),
INSERTIONDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS (NAME, CITY) VALUES ('ConTe.it', 'Roma');

CREATE TABLE EMPLOYEES (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(40),
SURNAME VARCHAR(40),
BIRTHDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);

INSERT INTO EMPLOYEES (NAME, SURNAME) VALUES ('Giovanni', 'Mezzullo');
